---
title: "Executive Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    visit_us: https://git.io/vaZdx
    theme: flatly
runtime: shiny
---

```{r setup, include=FALSE}
library(ggridges)
library(ggplot2)
library(viridis)
library(hrbrthemes)
library(flexdashboard)
library(readr)
library(tidyverse)
library(ggplot2)
library(bbplot)
library(tidyquant)
library(rvest)
library(ggthemes)
library(r2d3)
library(plotly)
library(maps)
library(ggmap)
library(GGally)
library(ggplot2)
library(dplyr) # easier data wrangling 
library(viridis) # colour blind friendly palette, works in B&W also
library(Interpol.T) #  will generate a large dataset on initial load
library(lubridate) # for easy date manipulation
library(ggExtra) # because remembering ggplot theme options is beyond me
library(tidyr) 
 
 
data <- data(Trentino_hourly_T,package = "Interpol.T")
 
names(h_d_t)[1:5]<- c("stationid","date","hour","temp","flag")
df <- tbl_df(h_d_t) %>%
  filter(stationid =="T0001")
 
df <- df %>% mutate(year = year(date),
                  month = month(date, label=TRUE),
                  day = day(date))
  
df$date<-ymd(df$date) # not necessary for plot but 
#useful if you want to do further work with the data
 
#cleanup
rm(list=c("h_d_t","mo_bias","Tn","Tx",
          "Th_int_list","calibration_l",
          "calibration_shape","Tm_list"))
 
 
#create plotting df
df <-df %>% select(stationid,day,hour,month,year,temp)%>%
        fill(temp) #optional - see note below
 
# Re: use of fill
# This code is for demonstrating a visualisation technique
# There are 5 missing F values in the dataframe.
 
# see the original plot here (from my ggplot demo earlier this year) to see the white spaces where the missing values occcur:
# https://github.com/johnmackintosh/ggplotdemo/blob/master/temp8.png 
 
# I used 'fill' from  tidyr to take the prior value for each missing value and replace the NA
# This is a quick fix for the blog post only - _do not_ do this with your real world data
 
# Should really use either use replace_NA or complete(with fill)in tidyr 
# OR 
# Look into more specialist way of replacing these missing values -e.g. imputation.
 
 
 
statno <-unique(df$stationid)
 
stocks <- 
read_csv('https://raw.githubusercontent.com/datasets/s-and-p-500-companies-financials/master/data/constituents.csv')

# Access to CRAN packages data stream
source("helpers.R")

# pkgStream is a reactive expression that represents a stream of
# new package download data; up to once a second it may return a
# data frame of new downloads since the last update.
pkgStream <- packageStream()

# pkgData is a reactive expression that accumulates previous values
# of pkgStream, discarding any that are older than maxAgeSecs.
maxAgeSecs <- 60 * 5 
pkgData <- packageData(pkgStream, maxAgeSecs)
```

```{r}
library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")


```

Sidebar {.sidebar}
=======================================================================

### Input Selections

Lorem ipsum forem
[jcheng5/cransim](https://github.com/jcheng5/cransim).

<style type="text/css"> .sidebar { overflow: auto; } </style>

```{r}
# Rate at which to flag high download traffic
# sliderInput("rateThreshold", "Warn when rate exceeds:",
#             min = 0, max = 50, value = 3, step = 0.1
# )

# Maximum number of raw data rows to keep
numericInput("maxrows", "Recent downloads window:", 50)

dateRangeInput("daterange1", "Date range:",
                 start = Sys.Date() - 362,
                 end   = Sys.Date())

selectizeInput(inputId = 'tickers', 
               label = 'tickers', 
               choices = stocks$Symbol, 
               selected = c('AAPL'), 
               multiple = FALSE,
               options = NULL)

```


```{r}

clean_stock_data <- reactive({
  stocks <- tidyquant::tq_get(
    c(input$tickers, 'SPY', 'DJI', 'AKRX'), 
    complete_cases = TRUE, 
    from = input$daterange1[[1]], 
    to = input$daterange1[[2]]
  )

clean_stock_data <- 
  stocks %>% 
  group_by(symbol) %>% 
  arrange(symbol, desc(date)) %>% 
  mutate(diff = (close - lead(close))/lead(close))
})


pivoted_stock_data <- reactive({
  clean_stock_data() %>% 
  select(symbol, diff, date) %>% 
  pivot_wider(names_from = symbol, values_from = diff) %>% 
  filter(complete.cases(.))
})

correl <- reactive({
  pivoted_stock_data() %>% 
    select(-date) %>% 
    cor
})

sigma_stock <- reactive({
  pivoted_stock_data() %>% 
    .[,2] %>% 
    unlist %>% 
    sd
})

sigma_market <- reactive({
  pivoted_stock_data() %>% 
    .[,3] %>% 
    unlist %>% 
    sd
})
```


Dashboard
=======================================================================

Row 
-----------------------------------------------------------------------

### Correlation

```{r}
# Emit the download rate
renderValueBox({
  value <- round(correl()[[3]], 2)
  valueBox(
    value = value,
    icon = "fa-area-chart",
    color = if (value >= .5) "warning" else "primary"
  )
})
```

### Alpha

```{r}
# Emit the download rate
renderValueBox({
  valueBox(
    value = 1.32,
    icon = "fa-area-chart",
    color = if (1.32 <= .5) "warning" else "primary"
  )
})
```


### Beta {.value-box} 

```{r}
# Emit the download rate
renderValueBox({
  value <- round(correl()[[3]], 2)
  valueBox(
    value = round(value*sigma_stock()/sigma_market(), 2),
    icon = "fa-area-chart",
    color = if (value <= .5) "warning" else "primary"
  )
})
```

### Delta {.value-box} 

```{r}
# Emit the download rate
renderValueBox({
  value <- round(correl()[[3]], 2)*2
  valueBox(
    value = round(value*sigma_stock()/sigma_market(), 2),
    icon = "fa-area-chart",
    color = if (value <= .5) "warning" else "primary"
  )
})
```

### Epsilon {.value-box} 

```{r}
# Emit the download rate
renderValueBox({
  value <- round(correl()[[3]], 2)^3
  valueBox(
    value = round(value*sigma_stock()/sigma_market(), 2),
    icon = "fa-area-chart",
    color = if (value <= .5) "warning" else "primary"
  )
})
```


<!-- ### Cap -->
<!-- ```{r} -->
<!-- renderGauge({ -->
<!--   gauge(42, min = 0, max = 100, symbol = '%', gaugeSectors( -->
<!--   success = c(80, 100), warning = c(40, 79), danger = c(0, 39) -->
<!-- )) -->
<!-- }) -->
<!-- ``` -->

### Unique users {.value-box}

```{r}
# usrCount is a reactive expression that keeps an approximate
# count of all of the unique users that have been seen since the
# app started.
usrCount <- userCount(pkgStream)

# Emit the user count
renderValueBox({
  valueBox(value = usrCount(), icon = "fa-users")
})
```

Row {data-height=550}
-----------------------------------------------------------------------

### Market Comparison 
```{r}
renderPlot({
  ggplot(clean_stock_data()) + 
    aes(x = date, y = close) + 
    geom_line() +
    facet_wrap(. ~ symbol, scales = 'free_y') +
    theme(axis.text.x=element_text(angle=45,hjust=1)) +
    # geom_bbands(aes(high = high, low = low, close = close, volume = volume),
    #                ma_fun = VWMA, n = 10) +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
})
```

### Diamond Pricing
```{r}
renderPlotly({
  d <- diamonds[sample(nrow(diamonds), 1000), ]

p <- plot_ly(
  d, x = ~carat, y = ~price,
  # Hover text:
  text = ~paste("Price: ", price, '$<br>Cut:', cut),
  color = ~carat, 
  size = ~carat,
  opacity = .3
)
p
})
```


### Heatmap {data-width=750}
```{r}

renderPlot({
  ######## Plotting starts here#####################
p <-ggplot(df,aes(day,hour,fill=temp))+
  geom_tile(color= "white",size=0.1) + 
  scale_fill_viridis(name="Hrly Temps C",option ="C")
p <-p + facet_grid(year~month)
p <-p + scale_y_continuous(trans = "reverse", breaks = unique(df$hour))
p <-p + scale_x_continuous(breaks =c(1,10,20,31))
p <-p + theme_minimal(base_size = 8)
# p <-p + labs(title= paste("Hourly Temps - Station",statno), x="Day", y="Hour Commencing")
p + theme(legend.position = "bottom")+
  theme(plot.title=element_text(size = 14))+
  theme(axis.text.y=element_text(size=6)) +
  theme(strip.background = element_rect(colour="white"))+
  theme(plot.title=element_text(hjust=0))+
  theme(axis.ticks=element_blank())+
  theme(axis.text=element_text(size=7))+
  theme(legend.position = "none") +
  removeGrid()#ggExtra
})
```
<!-- Column {data-width=400} -->
<!-- ------------------------------------- -->

<!-- ### Total downloads {.value-box} -->
<!-- ```{r} -->
<!-- gauge(50, min = 0, max = 100, symbol = '%', gaugeSectors( -->
<!--   success = c(80, 100), warning = c(40, 79), danger = c(0, 39) -->
<!-- )) -->
<!-- ``` -->

<!-- ### Total downloads {.value-box} -->
<!-- ```{r} -->
<!-- gauge(50, min = 0, max = 100, symbol = '%', gaugeSectors( -->
<!--   success = c(80, 100), warning = c(40, 79), danger = c(0, 39) -->
<!-- )) -->
<!-- ``` -->


Row {data-height=650}
-----------------------------------------------------------------------

### Percent of downloads (last 5 min) {data-width=440}

```{r}
renderD3({
  r2d3(data = read.csv("dji-latest.csv"), 
     d3_version = 4, 
     container = "div", 
     options = list(start = 2006, end = 2011), 
     script = "calendar.js")
})
```

### Processing - last 60 hours
```{r}
renderPlot({
  # library


# Plot
ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Temp. [F]", option = "C") +
  labs(title = 'Temperatures in Lincoln NE in 2016') +
  theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
})
```

### Chord Relationship
```{r}
r2d3::r2d3("cord.js", data = matrix(round(runif(16, 1, 10000)), ncol = 4, nrow = 4))
```

### Daily Return v. Market
```{r}
renderPlot({
  print(pivoted_stock_data())
  pivoted_stock_data() %>% 
    ggplot() +
    aes(x = SPY, y = !!sym(input$tickers)) +
    geom_density_2d(alpha = .4) +
    geom_point(alpha = 1, size = .5) +
    geom_smooth(method = lm, se = FALSE) +
    geom_vline(xintercept = 0, alpha = .3) +
    geom_hline(yintercept = 0, alpha = .3) +
    theme_tq() +
    xlim(-.05, .05) +
    ylim(-.05, .05) # 
})
```

Row {data-height=650}
-----------------------------------------------------------------------

### Polar
```{r}
renderPlotly({
 plot_ly(
    type = "funnel",
    name = 'Montreal',
    y = c("Website visit", "Downloads", "Potential customers", "Requested price"),
    x = c(120, 60, 30, 20),
    textinfo = "value+percent initial") %>%
  add_trace(
    type = "funnel",
    name = 'Toronto',
    orientation = "h",
    y = c("Website visit", "Downloads", "Potential customers", "Requested price", "invoice sent"),
    x = c(100, 60, 40, 30, 20),
    textposition = "inside",
    textinfo = "value+percent previous") %>%
  add_trace(
    type = "funnel",
    name = 'Vancouver',
    orientation = "h",
    y = c("Website visit", "Downloads", "Potential customers", "Requested price", "invoice sent", "Finalized"),
  x = c(90, 70, 50, 30, 10, 5),
  textposition = "outside",
  textinfo = "value+percent total") %>%
  layout(yaxis = list(categoryarray = c("Website visit", "Downloads", "Potential customers", "Requested price", "invoice sent", "Finalized")))

})
```

### Codecov Breakout 
<!-- {data-width=640} -->

```{r}
r2d3(data = jsonlite::read_json("flare.json"), d3_version = 4, script = "treemap.js")
```

### GGally
```{r}
renderPlot({
  # From the help page:
data(tips, package = "reshape")
ggpairs(
  tips[, c(1, 3, 4, 2)],
  upper = list(continuous = "density", combo = "box_no_facet"),
  lower = list(continuous = wrap("points", size = .1), combo = "dot_no_facet" )
)
})
```

### Leaflet
```{r}
renderLeaflet({
  m
})
```


Recent Downloads
=======================================================================

Team Structure
=======================================================================

Messages

=======================================================================


